### PR TITLE
chore: added commitlint support

### PR DESCRIPTION
**Pull request by skodamarthi**
# What Changed
Added Commitlint 
Also added husky pre-commit hook that triggers commitlint every time a contributor tries to commit.
This ensures that the correct commit conventions are followed as listed here https://www.conventionalcommits.org/en/v1.0.0/

# Why
Fix for https://github.com/intuit/LD-React-Components/issues/87
Todo:

- [ ] Add tests
- [ ] Add docs
- [ ] Add yourself to contributors (run `yarn contributors:add`))

### CODE REVIEW

**Comment by skodamarthi** [comment]
@poorpaddy Can you please review?

**Review by poorpaddy — APPROVED** [review]
Great idea and indeed it is important.

**Review by poorpaddy — CHANGES_REQUESTED** [review]
Can you resolve conflicts in your branch please? You may need to rebase.

**Comment by skodamarthi** [comment]
@poorpaddy Addressed the conflicts. Can you please check and merge the PR if changes are ok? Thanks!

**Comment by poorpaddy** [comment]
@all-contributors please add @skodamarthi for tests

**Comment by skodamarthi** [comment]
Thank you @poorpaddy Can you please add hacktoberfest-accepted label as well? Thank you!

**Pull request merged**
