### PR TITLE
Add test summary to circleci

### LINKED ISSUE #58: Add Test Summary for CircleCi
Based on CircleCi's documentation add Test Summaries. See documentation here: https://circleci.com/docs/2.0/configuration-reference/#store_test_results

### PR DESCRIPTION
**Pull request by tekgal**
# What Changed
fixes #58 
updated package.json "test" command definition to create test summary in junit format and also moves the junit.xml output file in desired path as specified in the circleci config.yaml
# Why
Circleci understands junit output format. 
Todo:

- [ ] Add tests
- [ ] Add docs
- [ ] Add yourself to contributors (run `yarn contributors:add`))

### CODE REVIEW

**Comment by tekgal** [comment]
@poorpaddy do you know why the "test" "lint" and "build" are stuck in pending state for the PR above?

**Comment by tekgal** [comment]
@poorpaddy this is how the test summary appears.
image

**Comment by tekgal** [comment]
@all-contributors please add tekgal for #61

**Comment by poorpaddy** [comment]
@all-contributors please add @tekgal for infra

**Comment by poorpaddy** [comment]
> @poorpaddy do you know why the "test" "lint" and "build" are stuck in pending state for the PR above?

That I am not sure. I haven't figured out why as I do not receive any errors. When I look at this PR though after the fact they seem to all pass. The only failure is the release which is fine because we don't want release to occur on a PR.

**Pull request merged**
