### PR TITLE
Follow-up to pull#59 (saving CircleCI test summaries)

### LINKED ISSUE #58: Add Test Summary for CircleCi
Based on CircleCi's documentation add Test Summaries. See documentation here: https://circleci.com/docs/2.0/configuration-reference/#store_test_results

### PR DESCRIPTION
**Pull request by funkadelic**
# What Changed
fixes #58 

- Added `jest-junit` as a devDependency
- Enabled jest junit test report
- store `coverage/` as an artifact
- added `./test-results` to `yarn clean`

confirmed working with the following job: https://app.circleci.com/jobs/github/funkadelic/LD-React-Components/67

# Why

Todo:

- [ ] Add tests
- [ ] Add docs
- [ ] Add yourself to contributors (run `yarn contributors:add`))

### CODE REVIEW

**Comment by poorpaddy** [comment]
@all-contributors please add @funkadelic for infra

**Comment by poorpaddy** [comment]
@all-contributors please add @funkadelic for infra

**Comment by poorpaddy** [comment]
I'm not actually seeing the test summaries being produced from this PR. I am however seeing it on the previous PR. Perhaps it is not a loss though since value is added with the .gitignore and clean up process added. If you revise this to just be those two changes I'll merge it as it will no longer be duplicative.

**Comment by funkadelic** [comment]
@poorpaddy yeah, i think the difference between my PR and the other one was that all changes were in `.circleci/config.yml` whereas the other one was in `package.json`. I had to merge down to master in my fork to get CircleCI to actually apply my `.circleci/config.yml` changes, which I think is why it didn't produce anything in this PR. Six of one, half a dozen of the other 😄

**Pull request merged**
